#╭────-·-ˋˏ-༻IMPORTS༺-ˎˊ·-────╮

import hashlib

#╰────-·-ˋˏ-༻IMPORTS༺-ˎˊ·-────╯

#╭────-·-ˋˏ-༻INSERT TITLE༺-ˎˊ·-────╮



#╰────-·-ˋˏ-༻INSERT TITLE༺-ˎˊ·-────╯

#╭────-·-ˋˏ-༻PKG PARAMETERS༺-ˎˊ·-────╮

PKG_p = 1004162036461488639338597000466705179253226703
PKG_q = 950133741151267522116252385927940618264103623
PKG_e = 973028207197278907211

#╰────-·-ˋˏ-༻PKG PARAMETERS༺-ˎˊ·-────╯

#╭────-·-ˋˏ-༻PROCUREMENT OFFICER RSA PARAMETERS༺-ˎˊ·-────╮

# use for secure delivery of the query response
PO_p = 1080954735722463992988394149602856332100628417
PO_q = 1158106283320086444890911863299879973542293243
PO_e = 106506253943651610547613

#╰────-·-ˋˏ-༻PROCUREMENT OFFICER RSA PARAMETERS༺-ˎˊ·-────╯

#╭────-·-ˋˏ-༻IDENTIFYING VALUES FOR EACH NODE༺-ˎˊ·-────╮



#╰────-·-ˋˏ-༻IDENTIFYING VALUES FOR EACH NODE༺-ˎˊ·-────╯

#identifying value for each node 
# this is used for the calculation of t_j = r_j ^e mod n 

# the harn multi-signautre process. 
inventory_identity = {
  "Inventory A": 126,
  "Inventory B": 127,
  "Inventory C": 128, 
  "Inventory D": 129, 
}

random_inventory_values = {
  "Inventory A": 621,
  "Inventory B": 721,
  "Inventory C": 821, 
  "Inventory D": 921, 
}

#The key derivation function 
# following the lectuure/tutorial method where:
#n = p * q 
#phi(N) = (p -1 ) (q-1)
# d = e^(-1) mod phi(n)

def compute_rsa(p,q,e):
  n = p * q 
  phi_n = (p-1) * (q-1)
  d = pow(e, -1, phi_n)
  return n, phi_n, d

# deriving private key componets where PKG public key = (PKG_e, PKG_n)
# PKG private = PKG_D

PKG_n, PKG_phi, PKG_d = compute_rsa(PKG_p, PKG_q, PKG_e)

#inventory secret keys

inventory_secret = {}
for node_nam, identity in inventory_identity.items():
  secret_key = pow(identity, PKG_d, PKG_n)
  inventory_secret[node_nam] = secret_key
  
#derive officerr public/private key components
# the officer private key = PO_D
# officer private key  = PO_d
PO_n, PO_phi, PO_d = compute_rsa(PO_p, PO_q, PO_e)

# generating secret key for each inventory identity
# harm scheme: t_j = r_j ^PKG-e mod PKG_n

inventory_values = {}
for node_nam, ran_value in random_inventory_values.items():
  t_j = pow(ran_value, PKG_e, PKG_n)
  inventory_values[node_nam] = t_j

#calculating the aggregated t value
# harn scheme: t = product(t_j) mod PKG_n

aggregate = 1
for t_j in inventory_values.values():
  aggregate = (aggregate * t_j) % PKG_n

#printing all the initialised and derived values for the UI
print("TASK 3: INITIALISE CRYPTOGRAPHIC PARAMETERS")

print("\n PKG PARAMETERS FOR HARN MULTI-SIGNATURES---")
print("PKG_p= ", PKG_p)
print("PKG_q= ", PKG_q)
print("PKG_e= ", PKG_e)
print("PKG_n= ", PKG_n)

print("PKG_phi= ", PKG_phi)

print("\n Procurement Officer parameters for secure delivery--")
print("PO_p =", PO_p)
print("PO_q =", PO_q)
print("PO_e =", PO_e)
print("PO_n =", PO_n)
print("PO_phi =", PO_phi)
print("PO_d =", PO_d)

print("\n Inventory Identities--")
for node_nam, identity in inventory_identity.items():
  print(node_nam, "ID=", identity)

print("\n Inventory Random values--")
for node_nam, ran_value in inventory_values.items():
  print(node_nam, "random value =", ran_value)

print("\n Inventory secret keys generated by PKG--")
for node_nam, secret_key in inventory_secret.items():
  print(node_nam, "g_j =", secret_key)
  # Aiza: is it supposed to print secret_key instead?

print("\n ---Inventory t_j values ----")
for node_nam, t_j in inventory_values.items():
  print(node_nam, "t_j=", t_j)

print("\n ---Aggregated t value ----")
print("t =", aggregate)

#-task2 question 2 or part 2 here ------
# authorised external user for this assingment scnceario 

authorised_user=  {
  "Procurement Officer": True
}

# stimulating the distributed inventory database
# these are assumed to be accepted and stored through task 1 and task 2

inventory_database = {
  "Inventory A": [
    {"item_id": "001", "qty": 32, "price": 12, "location": "D"},
    {"item_id": "002", "qty": 20, "price": 14, "location": "C"},
    {"item_id": "003", "qty": 22, "price": 16, "location": "B"},
    {"item_id": "004", "qty": 12, "price": 18, "location": "A"},
  ],
  "Inventory B": [
    {"item_id": "001", "qty": 32, "price": 12, "location": "D"},
    {"item_id": "002", "qty": 20, "price": 14, "location": "C"},
    {"item_id": "003", "qty": 22, "price": 16, "location": "B"},
    {"item_id": "004", "qty": 12, "price": 18, "location": "A"},
  ], 
  "Inventory C": [
    {"item_id": "001", "qty": 32, "price": 12, "location": "D"},
    {"item_id": "002", "qty": 20, "price": 14, "location": "C"},
    {"item_id": "003", "qty": 22, "price": 16, "location": "B"},
    {"item_id": "004", "qty": 12, "price": 18, "location": "A"},
  ],

  "Inventory D": [
    {"item_id": "001", "qty": 32, "price": 12, "location": "D"},
    {"item_id": "002", "qty": 20, "price": 14, "location": "C"},
    {"item_id": "003", "qty": 22, "price": 16, "location": "B"},
    {"item_id": "004", "qty": 12, "price": 18, "location": "A"},
  ],
}

def check_user(user_name):
  """
  Check whether if the external user is authorised to submit query.
  for this assignment scearioo, the procurement officer is treated as a authorised user. 
  """

  if user_name in authorised_user and authorised_user[user_name] == True:
    return True
  else: 
    return False

def search_item (node_database, item_id):
  """
  Searching inventory node for the request item ID.
  return the quantity if found.
  return none if the item does not exist. 
  """

  for record in node_database:
    if record["item_id"] == item_id: 
      return record["qty"]

  return None

def submit_request(user_name, item_id):
  """
  Allow all authorised external user to submit a request query
  to the distributed inventory system. 
  """ 

  print("Task 3 : Query REQUEST SUBMISSION")
  print("External user:", user_name)
  print("Requested item ID:  " , item_id)
  print()

  print("first, Check whether user is authorised or not")

  authorised  = check_user(user_name)

  if authorised == False:
    print("Authorisation : FAILED")
    print("This user is not authorised. ")
    print("Please try submit another query later")

    return None

  print("Authorisation: PASSED")
  print("AUTHORISED USER")
  print()

  print("Secondly, Sending this query to Inventory A,B, C and D ")
  print("Please wait")
  query_results = {}

  for node_nam, node_database in inventory_database.items():
    result = search_item(node_database, item_id)
    query_results[node_nam] = result
    print(node_nam, "Returned quantity here:  ", result)

    print()

    print("finally, query request has been completed")
    print("Collected node responses are:  ", query_results)

  return query_results

query_results = submit_request("Procurement Officer", "002")

#╭────-·-ˋˏ-༻COMPUTING HASH༺-ˎˊ·-────╮

def computing_hash(t, message):

    # combining t with message 
    combined = str(t) + str(message)
    
    # hashing using md5
    md5hash = hashlib.md5(combined.encode()).hexdigest()
    
    # converting hex to dec
    h = int(md5hash, 16)
    
    print("\n₊˚ ✧ ━━━━⊱Computing H(t,m)...⊰━━━━ ✧ ₊˚")
    print(f"Aggregated t: {t}")
    print(f"Message: {message}")
    print(f"Combined input (t + m): {combined}")
    print(f"MD5 hex: {md5hash}")
    print(f"H(t,m) decimal: {h}")
    
    return h

#╰────-·-ˋˏ-༻COMPUTING HASH༺-ˎˊ·-────╯

#╭────-·-ˋˏ-༻PARTIAL SIGNATURE GENERATION༺-ˎˊ·-────╮

def generating_partial_signatures(h, inv_secret, inv_values, PKG_n):
    
    partial_signatures = {}
    
    print("\n₊˚ ✧ ━━━━⊱Generating Partial Signatures...⊰━━━━ ✧ ₊˚")
    
    for node_name in inv_secret:
        gj = inv_secret[node_name]
        rj = inv_values[node_name]
        
        # harn scheme (sj = gj * rj^H(t,m) mod PKG_n)
        sj = (gj * pow(rj, h, PKG_n)) % PKG_n
        
        partial_signatures[node_name] = sj
        
        print(f"\n--- {node_name} ---")
        print(f"Secret key (gj): {gj}")
        print(f"Random value (rj): {rj}")
        print(f"Partial signature (sj): {sj}")
    
    return partial_signatures

#╰────-·-ˋˏ-༻PARTIAL SIGNATURE GENERATION༺-ˎˊ·-────╯

#╭────-·-ˋˏ-༻AGGREGATE SIGNATURES༺-ˎˊ·-────╮

def aggregate_signatures(partial_signatures, PKG_n):

    s = 1
    
    print("\n₊˚ ✧ ━━━━⊱Aggregating Signatures...⊰━━━━ ✧ ₊˚")
    
    for node_name, sj in partial_signatures.items():
        s = (s * sj) % PKG_n
        print(f"{node_name} partial signature (sj): {sj}")
    
    print(f"\nAggregated signature (s): {s}")
    
    return s

#╰────-·-ˋˏ-༻AGGREGATE SIGNATURES༺-ˎˊ·-────╯

#╭────-·-ˋˏ-༻MULTI-SIGNATURE VERIFICATION༺-ˎˊ·-────╮

def verify_multisig(s, t, h, inventory_identity, PKG_e, PKG_n):
    
    print("\n₊˚ ✧ ━━━━⊱Verifying Multi-Signature...⊰━━━━ ✧ ₊˚")
    
    # verification no.1 -  s^e mod n
    v1 = pow(s, PKG_e, PKG_n)
    print(f"\nVerification 1 = s^e mod n")
    print(f"Verification 1 = {v1}")
    
    # verification no.2 - product of all identities * t^H(t,m) mod n
    # multiplying the identities together
    identity_product = 1
    for node_name, identity in inventory_identity.items():
        identity_product = (identity_product * identity) % PKG_n
        print(f"{node_name} identity (ij): {identity}")
    
    print(f"\nProduct of all identities: {identity_product}")
    
    # compute t^H(t,m) mod n
    t_power = pow(t, h, PKG_n)
    print(f"t^H(t,m) mod n: {t_power}")
    
    # multiplying together
    v2 = (identity_product * t_power) % PKG_n
    print(f"\nVerification 2 = (i1*i2*i3*i4) * t^H(t,m) mod n")
    print(f"Verification 2 = {v2}")
    
    # comparing
    if v1 == v2:
        print("\n｡ﾟ•┈꒰ა ♡Multi-Signature is VALID♡ ໒꒱┈•｡ﾟ")
        return True
    else:
        print("\n｡ﾟ•┈꒰ა ♡Multi-Signature is INVALID♡ ໒꒱┈•｡ﾟ")
        return False

#╰────-·-ˋˏ-༻MULTI-SIGNATURE VERIFICATION༺-ˎˊ·-────╯

#╭────-·-ˋˏ-༻RSA ENCRYPTION༺-ˎˊ·-────╮

def encrypt_response(message, PO_e, PO_n):
    # converting message to a number
    m = int(hashlib.md5(str(message).encode()).hexdigest(), 16)
    
    # RSA encryption (c = m^e mod n)
    c = pow(m, PO_e, PO_n)
    
    print("\n₊˚ ✧ ━━━━⊱Encrypting Response...⊰━━━━ ✧ ₊˚")
    print(f"Original message: {message}")
    print(f"Message as number (m): {m}")
    print(f"Encrypted message (c): {c}")
    
    return c, m

#╰────-·-ˋˏ-༻RSA ENCRYPTION༺-ˎˊ·-────╯

#╭────-·-ˋˏ-༻RSA DECRYPTION༺-ˎˊ·-────╮

def decrypt_response(c, m, PO_d, PO_n):
    
    # RSA decryption (m = c^d mod n)
    decrypted = pow(c, PO_d, PO_n)
    
    print("\n₊˚ ✧ ━━━━⊱Decrypting Response...⊰━━━━ ✧ ₊˚")
    print(f"Encrypted message (c): {c}")
    print(f"Decrypted message (m): {decrypted}")
    
    # verifying decryption by comparing with original m
    if decrypted == m:
        print("\n｡ﾟ•┈꒰ა ♡Decryption SUCCESSFUL♡ ໒꒱┈•｡ﾟ")
        print(f"Procurement Officer successfully recovered the message!")
    else:
        print("\n｡ﾟ•┈꒰ა ♡Decryption FAILED♡ ໒꒱┈•｡ﾟ")
    
    return decrypted

#╰────-·-ˋˏ-༻RSA DECRYPTION༺-ˎˊ·-────╯

#╭────-·-ˋˏ-༻MAIN WORKFLOW༺-ˎˊ·-────╮

def multisig_workflow(query_results, aggregate, inventory_secret, inventory_values, inventory_identity, PKG_e, PKG_n, PO_e, PO_n, PO_d):

    print("\n₊˚ ✧ ━━━━⊱TASK 3: MULTI-SIGNATURE WORKFLOW⊰━━━━ ✧ ₊˚")

    # getting the message from query
    # all nodes should return same quantity
    message = str(query_results)

    # computing H(t,m)
    h = computing_hash(aggregate, message)

    # generating partial signatures from each node
    partial_signatures = generating_partial_signatures(h, inventory_secret, inventory_values, PKG_n)

    # aggregate all partial signatures to one
    s = aggregate_signatures(partial_signatures, PKG_n)

    # verifying the multi-signature
    print("\n₊˚ ✧ ━━━━⊱Consensus Check⊰━━━━ ✧ ₊˚")
    is_valid = verify_multisig(s, aggregate, h, inventory_identity, PKG_e, PKG_n)

    if is_valid == False:
        print("Multi-signature verification failed. Response will not be sent.")
        return None

    # encrypt
    c, m = encrypt_response(message, PO_e, PO_n)

    # decrypt
    decrypted = decrypt_response(c, m, PO_d, PO_n)

    print("\n₊˚ ✧ ━━━━⊱WORKFLOW COMPLETE⊰━━━━ ✧ ₊˚")
    print("Query result successfully verified, encrypted and delivered!")

    return decrypted

#╰────-·-ˋˏ-༻MAIN WORKFLOW༺-ˎˊ·-────╯

multisig_workflow(query_results, aggregate, inventory_secret, random_inventory_values, inventory_identity, PKG_e, PKG_n, PO_e, PO_n, PO_d)


