PKG_p = 1004162036461488639338597000466705179253226703
PKG_q = 950133741151267522116252385927940618264103623
PKG_e = 973028207197278907211
# the PKG parameters for harn identity based multi signature 
# values from the assingment list of keys and part 2


PO_p = 1080954735722463992988394149602856332100628417
PO_q = 1158106283320086444890911863299879973542293243
PO_e = 106506253943651610547613
# the procurement officer RSA paramets
# use for secure delivery of the query response
# these values from list of keys, part 2


#identifying value for each node 
# this is used for the calculation of t_j = r_j ^e mod n 

# the harn multi-signautre process. 
inventory_identity = {
  "Inventory A": 126,
  "Inventory B": 127,
  "Inventory C": 128, 
  "Inventory D": 129, 
}

inventory_values = {
  "Inventory A": 621,
  "Inventory B": 721,
  "Inventory C": 821, 
  "Inventory D": 921, 
}

#The key derivation function 
# following the lectuure/tutorial method where:
#n = p * q 
#phi(N) = (p -1 ) (q-1)
# d = e^(-1) mod phi(n)

def compute_rsa(p,q,e):
  n = p * q 
phi_n = ((p-1) * (q-1)
         d = pow(e, -1, phi_n)
return n, phi_n, d

# deriving private key componets where PKG public key = (PKG_e, PKG_n)
# PKG private = PKG_D

PKG_n, PKG_phi, PKG_d = computer_rsa(PKG_p, PKG_q, PKG_e)

#inventory secret keys

inventory_secret = {}
for node_nam, identity in inventory_identity.items():
  secret_key = pow(identity, PKG_, PKG_n)
  inventory_secret[node_nam] = secret_key
  
#derive officerr public/private key components
# the officer private key = PO_D
# officer private key  = PO_d
PO_n, PO_phi, PO_d = compute_rsa(PO_p, PO_q, PO_e)

# generating secret key for each inventory identity
# harm scheme: t_j = r_j ^PKG-e mod PKG_n

inventory_valuess = {}
for node_nam, ran_value in inventory_value.items():
  t_j = pow(ran_value, PKG_e, PKG_n)
  inventory_valuess[node_nam] = t_j

#calculating the aggregated t value
# harn scheme: t = product(t_j) mod PKG_n

aggregate = 1
for t_j in inventory_valuess.values():
  aggregate = (aggregate * t_j) % PKG_n

#printing all the initialised and derived values for the UI
print("TASK 3: INITIALISE CRYPTOGRAPHIC PARAMETERS")

print("\n PKG PARAMETERS FOR HARN MULTI-SIGNATURES---")
print("PKG_p= ", PKG_p)
print("PKG_q= ", PKG_q)
print("PKG_e= ", PKG_e)
print("PKG_n= ", PKG_n)

print("PKG_phi= ", PKG_phi)

print("\n Procurement Officer parameters for secure delivery--")
print("PO_p =", PO_p)
print("PO_q =", PO_q)
print("PO_e =", PO_e)
print("PO_n =", PO_n)
print("PO_phi =", PO_phi)
print("PO_d =", PO_d)

print("\n Inventory Identities--")
for node_nam, identity in inventory_identity.items():
  print(node_nam, "ID=", identity)

print("\n Inventory Random values--")
for node_nam, ran_value in inventory_values.items():
  print(node_nam, "random value =", ran_value)
print("\n Inventory secret keys generated by PKG--")
for node_nam, secret_key in inventory_secret.items():
  print(node_nam, "g_j =", t_j)

print("\n ---Inventory t_j values ----")
for node_nam, t_j in inventory_value.items():
  print(node_nam, "t_j=", t_j)

  print("\n ---Aggregated t value ----")
  print("t =", aggregate)



#-task2 question 2 or part 2 here ------
# authorised external user for this assingment scnceario 

authorised_user=  {
  "Procurement officer": True
}

# stimulating the distributed inventory database
# these are assumed to be accepted and stored through task 1 and task 2

inventory_database = {
  "Inventory A": [
    {"item_id": "001", "qty": 32, "price": 12, "location": "D"},
    {"item_id": "002", "qty": 20, "price": 14, "location": "C"},
    {"item_id": "003", "qty": 22, "price": 16, "location": "B"},
    {"item_id": "004", "qty": 12, "price": 18, "location": "A"},
  ]; 

  "Inventory B": [
    {"item_id": "001", "qty": 32, "price": 12, "location": "D"},
    {"item_id": "002", "qty": 20, "price": 14, "location": "C"},
    {"item_id": "003", "qty": 22, "price": 16, "location": "B"},
    {"item_id": "004", "qty": 12, "price": 18, "location": "A"},
  ]; 
  "Inventory C": [
    {"item_id": "001", "qty": 32, "price": 12, "location": "D"},
    {"item_id": "002", "qty": 20, "price": 14, "location": "C"},
    {"item_id": "003", "qty": 22, "price": 16, "location": "B"},
    {"item_id": "004", "qty": 12, "price": 18, "location": "A"},
  ]; 

  "Inventory D": [
    {"item_id": "001", "qty": 32, "price": 12, "location": "D"},
    {"item_id": "002", "qty": 20, "price": 14, "location": "C"},
    {"item_id": "003", "qty": 22, "price": 16, "location": "B"},
    {"item_id": "004", "qty": 12, "price": 18, "location": "A"},
  ]; 
}

def check_user(user_name):
  """
  Check whether if the external user is authorised to submit query.
  for this assignment scearioo, the procurement officer is treated as a authorised user. 
  """

if user_name in authorised_user and authorised_user[user_name] == True;
return True
else: 
return False

def search_item (node_database, item_id):
  """
  Searching inventory node for the request item ID.
  return the quantity if found.
  return none if the item does not exist. 
  """

for record in node_database:
  if record["item_id"] == item_id: 
  return record["qty"]

return None

def submit_request(user_name, item_id):

  """
  Allow all authorised external user to submit a request query
  to the distributed inventory system. 
  """ 

print("Task 3 : Query REQUEST SUBMISSION")
print("External user:", user_name)
print("Requested item ID:  " , item_id)
print()

print("first, Check whether user is authorised or not")

authorised  = check_user(user_name)

if authorised == False:
  print("Authorisation : FAILED")
  print("This user is not authorised. ")
  print("Please try submit another query later")

return None

print("Authorisation: PASSED")
print("AUTHORISED USER")
print()

print("Secondly, Sending this query to Inventory A,B, C and D ")
print("Please wait")
query_results = {}

for node-nam, node_database in inventory_database.items():
  result = search_item(node_database, item_id)
  query_results[node_nam] = result
  print(node_nam, "Returned quantity here:  ", result)

print()

Print("finally, query request has been completed")
print("Collected node responses are:  ", query_results)

return query_results

query_results = submit_request("Procurement Officer", "002")

